CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1-10: Identity / resource
CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) UNIQUE NOT NULL, description TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(150) UNIQUE NOT NULL, description TEXT);
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), entra_object_id VARCHAR(255) UNIQUE, email VARCHAR(255) UNIQUE NOT NULL, name VARCHAR(200) NOT NULL, status VARCHAR(30) DEFAULT 'ACTIVE', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE user_roles (user_id UUID REFERENCES users(id) ON DELETE CASCADE, role_id UUID REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id, role_id));
CREATE TABLE resources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(200) NOT NULL, email VARCHAR(255), resource_type VARCHAR(30) DEFAULT 'INTERNAL', employment_type VARCHAR(50), designation VARCHAR(150), experience_years NUMERIC(5,2), location VARCHAR(150), entity VARCHAR(150), status VARCHAR(40) DEFAULT 'ACTIVE', zoho_employee_id VARCHAR(150) UNIQUE, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE skills (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(150) UNIQUE NOT NULL, category VARCHAR(100), description TEXT);
CREATE TABLE resource_skills (resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, skill_id UUID REFERENCES skills(id) ON DELETE CASCADE, proficiency VARCHAR(50), years_experience NUMERIC(5,2), is_primary BOOLEAN DEFAULT false, PRIMARY KEY(resource_id, skill_id));
CREATE TABLE resource_availability (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, start_date DATE NOT NULL, end_date DATE NOT NULL, available_percent NUMERIC(5,2) CHECK(available_percent BETWEEN 0 AND 100), source VARCHAR(50));
CREATE TABLE leave_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, start_date DATE NOT NULL, end_date DATE NOT NULL, leave_type VARCHAR(80), status VARCHAR(40) DEFAULT 'APPROVED', external_id VARCHAR(150));
CREATE TABLE holiday_calendars (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(150) NOT NULL, client_name VARCHAR(200), year INT NOT NULL, UNIQUE(name,year));

-- 11-20: client / demand / matching
CREATE TABLE accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(200) NOT NULL, owner_user_id UUID REFERENCES users(id), entity VARCHAR(150), status VARCHAR(40) DEFAULT 'ACTIVE');
CREATE TABLE projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_code VARCHAR(100) UNIQUE NOT NULL, account_id UUID NOT NULL REFERENCES accounts(id), name VARCHAR(200) NOT NULL, project_manager_id UUID REFERENCES users(id), entity VARCHAR(150), start_date DATE, end_date DATE, status VARCHAR(40) DEFAULT 'ACTIVE');
CREATE TABLE project_members (project_id UUID REFERENCES projects(id) ON DELETE CASCADE, resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, role_name VARCHAR(150), joined_at DATE, released_at DATE, PRIMARY KEY(project_id,resource_id));
CREATE TABLE requirements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), requirement_code VARCHAR(100) UNIQUE NOT NULL, project_id UUID NOT NULL REFERENCES projects(id), title VARCHAR(250) NOT NULL, description TEXT, resource_count INT DEFAULT 1, role_name VARCHAR(150), min_experience_years NUMERIC(5,2), location VARCHAR(150), start_date DATE, end_date DATE, allocation_percent NUMERIC(5,2), priority VARCHAR(40), certainty_percent NUMERIC(5,2), status VARCHAR(50) DEFAULT 'OPEN', created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE requirement_skills (requirement_id UUID REFERENCES requirements(id) ON DELETE CASCADE, skill_id UUID REFERENCES skills(id), required_proficiency VARCHAR(50), min_years NUMERIC(5,2), is_mandatory BOOLEAN DEFAULT true, PRIMARY KEY(requirement_id,skill_id));
CREATE TABLE match_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), requirement_id UUID REFERENCES requirements(id) ON DELETE CASCADE, run_type VARCHAR(50) DEFAULT 'HYBRID', model_name VARCHAR(150), status VARCHAR(40) DEFAULT 'COMPLETED', created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE match_results (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), match_run_id UUID REFERENCES match_runs(id) ON DELETE CASCADE, resource_id UUID REFERENCES resources(id), rule_score NUMERIC(7,3), ai_score NUMERIC(7,3), final_score NUMERIC(7,3), recommendation_reason TEXT, rank INT, decision VARCHAR(50));
CREATE TABLE allocations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), requirement_id UUID REFERENCES requirements(id), project_id UUID NOT NULL REFERENCES projects(id), resource_id UUID NOT NULL REFERENCES resources(id), start_date DATE NOT NULL, end_date DATE, allocation_percent NUMERIC(5,2) CHECK(allocation_percent BETWEEN 0 AND 100), role_name VARCHAR(150), rate NUMERIC(14,2), currency VARCHAR(10), status VARCHAR(40) DEFAULT 'ACTIVE', created_by UUID REFERENCES users(id));
CREATE TABLE allocation_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), allocation_id UUID REFERENCES allocations(id) ON DELETE CASCADE, action VARCHAR(80) NOT NULL, old_value JSONB, new_value JSONB, changed_by UUID REFERENCES users(id), changed_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE capacity_snapshots (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, snapshot_date DATE NOT NULL, capacity_percent NUMERIC(5,2), allocated_percent NUMERIC(5,2), available_percent NUMERIC(5,2), UNIQUE(resource_id,snapshot_date));

-- 21-29: timesheet / SOW / commercial
CREATE TABLE timesheets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_id UUID REFERENCES resources(id), project_id UUID REFERENCES projects(id), period_start DATE NOT NULL, period_end DATE NOT NULL, status VARCHAR(40) DEFAULT 'DRAFT', submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ);
CREATE TABLE timesheet_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), timesheet_id UUID REFERENCES timesheets(id) ON DELETE CASCADE, work_date DATE NOT NULL, hours NUMERIC(6,2) CHECK(hours>=0), work_type VARCHAR(100), description TEXT);
CREATE TABLE timesheet_exceptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), timesheet_id UUID REFERENCES timesheets(id) ON DELETE CASCADE, exception_type VARCHAR(100) NOT NULL, message TEXT NOT NULL, status VARCHAR(40) DEFAULT 'OPEN', resolved_by UUID REFERENCES users(id), resolved_at TIMESTAMPTZ);
CREATE TABLE sows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sow_code VARCHAR(100) UNIQUE NOT NULL, account_id UUID NOT NULL REFERENCES accounts(id), project_id UUID REFERENCES projects(id), title VARCHAR(250) NOT NULL, status VARCHAR(50) DEFAULT 'DRAFT', start_date DATE, end_date DATE, current_version INT DEFAULT 1, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE sow_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sow_id UUID REFERENCES sows(id) ON DELETE CASCADE, version_no INT NOT NULL, scope TEXT, commercial_summary TEXT, effective_from DATE, effective_to DATE, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(sow_id,version_no));
CREATE TABLE sow_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sow_id UUID REFERENCES sows(id) ON DELETE CASCADE, version_id UUID REFERENCES sow_versions(id), file_name VARCHAR(255) NOT NULL, sharepoint_url TEXT, document_hash VARCHAR(255), uploaded_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE sow_approvals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sow_id UUID REFERENCES sows(id) ON DELETE CASCADE, version_id UUID REFERENCES sow_versions(id), approver_role VARCHAR(100) NOT NULL, approver_user_id UUID REFERENCES users(id), status VARCHAR(40) DEFAULT 'PENDING', comments TEXT, acted_at TIMESTAMPTZ);
CREATE TABLE rate_cards (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(200) NOT NULL, account_id UUID REFERENCES accounts(id), entity VARCHAR(150), currency VARCHAR(10), status VARCHAR(40) DEFAULT 'ACTIVE');
CREATE TABLE rate_card_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rate_card_id UUID REFERENCES rate_cards(id) ON DELETE CASCADE, version_no INT NOT NULL, role_name VARCHAR(150), skill_id UUID REFERENCES skills(id), rate NUMERIC(14,2) NOT NULL, valid_from DATE, valid_to DATE);

-- 30-41: external / pipeline / release / system
CREATE TABLE external_organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(200) UNIQUE NOT NULL, organization_type VARCHAR(80), contact_email VARCHAR(255), status VARCHAR(40) DEFAULT 'ACTIVE');
CREATE TABLE external_resources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), external_org_id UUID REFERENCES external_organizations(id), resource_code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(200) NOT NULL, email VARCHAR(255), skills_summary TEXT, status VARCHAR(40) DEFAULT 'ACTIVE');
CREATE TABLE external_resource_contracts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), external_resource_id UUID REFERENCES external_resources(id) ON DELETE CASCADE, project_id UUID REFERENCES projects(id), contract_start DATE, contract_end DATE, rate NUMERIC(14,2), currency VARCHAR(10), po_reference VARCHAR(150), status VARCHAR(40) DEFAULT 'ACTIVE');
CREATE TABLE pipeline_leads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_id UUID REFERENCES accounts(id), title VARCHAR(250) NOT NULL, expected_start_date DATE, probability_percent NUMERIC(5,2), estimated_resource_count INT, status VARCHAR(50) DEFAULT 'OPEN', owner_user_id UUID REFERENCES users(id));
CREATE TABLE forecasts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), account_id UUID REFERENCES accounts(id), forecast_period DATE NOT NULL, skill_id UUID REFERENCES skills(id), demand_count INT, available_count INT, gap_count INT, confidence_percent NUMERIC(5,2));
CREATE TABLE releases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), resource_id UUID NOT NULL REFERENCES resources(id), project_id UUID NOT NULL REFERENCES projects(id), release_date DATE NOT NULL, reason TEXT, status VARCHAR(50) DEFAULT 'INITIATED', created_by UUID REFERENCES users(id));
CREATE TABLE release_checklists (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), release_id UUID REFERENCES releases(id) ON DELETE CASCADE, template_name VARCHAR(200) NOT NULL, status VARCHAR(40) DEFAULT 'OPEN');
CREATE TABLE checklist_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), release_checklist_id UUID REFERENCES release_checklists(id) ON DELETE CASCADE, item_name VARCHAR(200) NOT NULL, category VARCHAR(100), is_mandatory BOOLEAN DEFAULT true, status VARCHAR(40) DEFAULT 'PENDING', completed_by UUID REFERENCES users(id), completed_at TIMESTAMPTZ, comments TEXT);
CREATE TABLE assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_code VARCHAR(100) UNIQUE NOT NULL, asset_type VARCHAR(100), description TEXT, serial_number VARCHAR(150), status VARCHAR(40) DEFAULT 'AVAILABLE');
CREATE TABLE asset_assignments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID REFERENCES assets(id), resource_id UUID REFERENCES resources(id), project_id UUID REFERENCES projects(id), assigned_at TIMESTAMPTZ DEFAULT now(), returned_at TIMESTAMPTZ, status VARCHAR(40) DEFAULT 'ASSIGNED');
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, notification_type VARCHAR(100), title VARCHAR(250) NOT NULL, message TEXT NOT NULL, entity_type VARCHAR(100), entity_id UUID, is_read BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE audit_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id UUID, old_value JSONB, new_value JSONB, created_at TIMESTAMPTZ DEFAULT now());

-- indexes
CREATE INDEX idx_resources_status ON resources(status);
CREATE INDEX idx_resource_availability_dates ON resource_availability(resource_id,start_date,end_date);
CREATE INDEX idx_requirements_project_status ON requirements(project_id,status);
CREATE INDEX idx_allocations_resource_dates ON allocations(resource_id,start_date,end_date);
CREATE INDEX idx_timesheets_resource_period ON timesheets(resource_id,period_start,period_end);
CREATE INDEX idx_sow_status ON sows(status);
CREATE INDEX idx_sow_approvals_status ON sow_approvals(sow_id,status);
CREATE INDEX idx_audit_entity ON audit_events(entity_type,entity_id);
