'use client';
import { FormEvent, useState } from 'react';
import { LockKeyhole, ShieldCheck, ArrowRight } from 'lucide-react';
import './login.css';
export default function Login(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError(''); const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})}); const d=await r.json(); if(r.ok){location.href='/dashboard'}else setError(d.error?.message||'Login failed'); setLoading(false)}
 return <main className="login-shell"><section className="login-brand"><div className="brand-mark">dT</div><div><h1>diTrinity IRMS</h1><p>AI-enabled Resource & Operations Management</p></div><div className="brand-copy"><h2>One control plane for demand, people and delivery.</h2><p>Resource allocation, SOW lifecycle, timesheets, forecasting, integrations and management analytics in one governed workspace.</p><div className="security-row"><ShieldCheck size={18}/> Entra SSO ready · RBAC · Audit trail</div></div></section><section className="login-card"><div className="lock"><LockKeyhole size={20}/></div><h2>Sign in</h2><p className="muted">Use the configured development account or Microsoft Entra SSO.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@ditrinity.com"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="••••••••"/></label>{error&&<div className="form-error">{error}</div>}<button disabled={loading}>{loading?'Signing in…':'Sign in'} <ArrowRight size={17}/></button></form><div className="or"><span>or</span></div><a className="entra" href="/api/auth/entra">Continue with Microsoft Entra ID</a><p className="login-note">For local setup, configure <code>DEV_AUTH_EMAIL</code> and <code>DEV_AUTH_PASSWORD</code>. Production should use Entra.</p></section></main>
}
